/** Offline Goal protocol. Only an exact last line is actionable; missing markers pause. */
export const GOAL_MARKER_INSTRUCTION = '\n\nFor this Goal session only: at the end of each final reply, write exactly one separate last line: [[COS_GOAL:COMPLETE]] if the entire requested task is finished, or [[COS_GOAL:CONTINUE]] if requested work remains. Do not claim completion for partial work. If user input is required, explain it and omit both markers.';
export const GOAL_CONTINUATIONS: readonly string[] = [
  "Keep going until the requested work is finished. Stay within what I asked for.",
  "Keep going until the requested work is finished. Use the context already in this conversation.",
  "Keep going until the requested work is finished. Do the next concrete step now.",
  "Keep going until the requested work is finished. Do not add unrelated work.",
  "Keep going until the requested work is finished. Keep the original requirements in view.",
  "Keep going until the requested work is finished. Focus on the parts that are still incomplete.",
  "Keep going until the requested work is finished. Respect the constraints I already gave you.",
  "Keep going until the requested work is finished. Use the results you already have.",
  "Keep going until the requested work is finished. Keep the update brief and get back to the work.",
  "Keep going until the requested work is finished. Stop when the requested goal is fully complete.",
  "Finish the unfinished parts of my request. Stay within what I asked for.",
  "Finish the unfinished parts of my request. Use the context already in this conversation.",
  "Finish the unfinished parts of my request. Do the next concrete step now.",
  "Finish the unfinished parts of my request. Do not add unrelated work.",
  "Finish the unfinished parts of my request. Keep the original requirements in view.",
  "Finish the unfinished parts of my request. Focus on the parts that are still incomplete.",
  "Finish the unfinished parts of my request. Respect the constraints I already gave you.",
  "Finish the unfinished parts of my request. Use the results you already have.",
  "Finish the unfinished parts of my request. Keep the update brief and get back to the work.",
  "Finish the unfinished parts of my request. Stop when the requested goal is fully complete.",
  "Continue the task from where you left off. Stay within what I asked for.",
  "Continue the task from where you left off. Use the context already in this conversation.",
  "Continue the task from where you left off. Do the next concrete step now.",
  "Continue the task from where you left off. Do not add unrelated work.",
  "Continue the task from where you left off. Keep the original requirements in view.",
  "Continue the task from where you left off. Focus on the parts that are still incomplete.",
  "Continue the task from where you left off. Respect the constraints I already gave you.",
  "Continue the task from where you left off. Use the results you already have.",
  "Continue the task from where you left off. Keep the update brief and get back to the work.",
  "Continue the task from where you left off. Stop when the requested goal is fully complete.",
  "Get back to the concrete work that remains. Stay within what I asked for.",
  "Get back to the concrete work that remains. Use the context already in this conversation.",
  "Get back to the concrete work that remains. Do the next concrete step now.",
  "Get back to the concrete work that remains. Do not add unrelated work.",
  "Get back to the concrete work that remains. Keep the original requirements in view.",
  "Get back to the concrete work that remains. Focus on the parts that are still incomplete.",
  "Get back to the concrete work that remains. Respect the constraints I already gave you.",
  "Get back to the concrete work that remains. Use the results you already have.",
  "Get back to the concrete work that remains. Keep the update brief and get back to the work.",
  "Get back to the concrete work that remains. Stop when the requested goal is fully complete.",
  "Carry the original request through to completion. Stay within what I asked for.",
  "Carry the original request through to completion. Use the context already in this conversation.",
  "Carry the original request through to completion. Do the next concrete step now.",
  "Carry the original request through to completion. Do not add unrelated work.",
  "Carry the original request through to completion. Keep the original requirements in view.",
  "Carry the original request through to completion. Focus on the parts that are still incomplete.",
  "Carry the original request through to completion. Respect the constraints I already gave you.",
  "Carry the original request through to completion. Use the results you already have.",
  "Carry the original request through to completion. Keep the update brief and get back to the work.",
  "Carry the original request through to completion. Stop when the requested goal is fully complete.",
  "Complete the next unfinished requirement. Stay within what I asked for.",
  "Complete the next unfinished requirement. Use the context already in this conversation.",
  "Complete the next unfinished requirement. Do the next concrete step now.",
  "Complete the next unfinished requirement. Do not add unrelated work.",
  "Complete the next unfinished requirement. Keep the original requirements in view.",
  "Complete the next unfinished requirement. Focus on the parts that are still incomplete.",
  "Complete the next unfinished requirement. Respect the constraints I already gave you.",
  "Complete the next unfinished requirement. Use the results you already have.",
  "Complete the next unfinished requirement. Keep the update brief and get back to the work.",
  "Complete the next unfinished requirement. Stop when the requested goal is fully complete.",
  "Follow through on the work you just identified. Stay within what I asked for.",
  "Follow through on the work you just identified. Use the context already in this conversation.",
  "Follow through on the work you just identified. Do the next concrete step now.",
  "Follow through on the work you just identified. Do not add unrelated work.",
  "Follow through on the work you just identified. Keep the original requirements in view.",
  "Follow through on the work you just identified. Focus on the parts that are still incomplete.",
  "Follow through on the work you just identified. Respect the constraints I already gave you.",
  "Follow through on the work you just identified. Use the results you already have.",
  "Follow through on the work you just identified. Keep the update brief and get back to the work.",
  "Follow through on the work you just identified. Stop when the requested goal is fully complete.",
  "Keep working toward the stated finish line. Stay within what I asked for.",
  "Keep working toward the stated finish line. Use the context already in this conversation.",
  "Keep working toward the stated finish line. Do the next concrete step now.",
  "Keep working toward the stated finish line. Do not add unrelated work.",
  "Keep working toward the stated finish line. Keep the original requirements in view.",
  "Keep working toward the stated finish line. Focus on the parts that are still incomplete.",
  "Keep working toward the stated finish line. Respect the constraints I already gave you.",
  "Keep working toward the stated finish line. Use the results you already have.",
  "Keep working toward the stated finish line. Keep the update brief and get back to the work.",
  "Keep working toward the stated finish line. Stop when the requested goal is fully complete.",
  "Resolve what is still missing from my request. Stay within what I asked for.",
  "Resolve what is still missing from my request. Use the context already in this conversation.",
  "Resolve what is still missing from my request. Do the next concrete step now.",
  "Resolve what is still missing from my request. Do not add unrelated work.",
  "Resolve what is still missing from my request. Keep the original requirements in view.",
  "Resolve what is still missing from my request. Focus on the parts that are still incomplete.",
  "Resolve what is still missing from my request. Respect the constraints I already gave you.",
  "Resolve what is still missing from my request. Use the results you already have.",
  "Resolve what is still missing from my request. Keep the update brief and get back to the work.",
  "Resolve what is still missing from my request. Stop when the requested goal is fully complete.",
  "Pick up the remaining work and finish it. Stay within what I asked for.",
  "Pick up the remaining work and finish it. Use the context already in this conversation.",
  "Pick up the remaining work and finish it. Do the next concrete step now.",
  "Pick up the remaining work and finish it. Do not add unrelated work.",
  "Pick up the remaining work and finish it. Keep the original requirements in view.",
  "Pick up the remaining work and finish it. Focus on the parts that are still incomplete.",
  "Pick up the remaining work and finish it. Respect the constraints I already gave you.",
  "Pick up the remaining work and finish it. Use the results you already have.",
  "Pick up the remaining work and finish it. Keep the update brief and get back to the work.",
  "Pick up the remaining work and finish it. Stop when the requested goal is fully complete.",
  "Turn the next announced step into completed work. Stay within what I asked for.",
  "Turn the next announced step into completed work. Use the context already in this conversation.",
  "Turn the next announced step into completed work. Do the next concrete step now.",
  "Turn the next announced step into completed work. Do not add unrelated work.",
  "Turn the next announced step into completed work. Keep the original requirements in view.",
  "Turn the next announced step into completed work. Focus on the parts that are still incomplete.",
  "Turn the next announced step into completed work. Respect the constraints I already gave you.",
  "Turn the next announced step into completed work. Use the results you already have.",
  "Turn the next announced step into completed work. Keep the update brief and get back to the work.",
  "Turn the next announced step into completed work. Stop when the requested goal is fully complete.",
  "Continue with the remaining requested changes. Stay within what I asked for.",
  "Continue with the remaining requested changes. Use the context already in this conversation.",
  "Continue with the remaining requested changes. Do the next concrete step now.",
  "Continue with the remaining requested changes. Do not add unrelated work.",
  "Continue with the remaining requested changes. Keep the original requirements in view.",
  "Continue with the remaining requested changes. Focus on the parts that are still incomplete.",
  "Continue with the remaining requested changes. Respect the constraints I already gave you.",
  "Continue with the remaining requested changes. Use the results you already have.",
  "Continue with the remaining requested changes. Keep the update brief and get back to the work.",
  "Continue with the remaining requested changes. Stop when the requested goal is fully complete.",
  "Work through the unresolved items in my request. Stay within what I asked for.",
  "Work through the unresolved items in my request. Use the context already in this conversation.",
  "Work through the unresolved items in my request. Do the next concrete step now.",
  "Work through the unresolved items in my request. Do not add unrelated work.",
  "Work through the unresolved items in my request. Keep the original requirements in view.",
  "Work through the unresolved items in my request. Focus on the parts that are still incomplete.",
  "Work through the unresolved items in my request. Respect the constraints I already gave you.",
  "Work through the unresolved items in my request. Use the results you already have.",
  "Work through the unresolved items in my request. Keep the update brief and get back to the work.",
  "Work through the unresolved items in my request. Stop when the requested goal is fully complete.",
  "Bring the requested task to its actual conclusion. Stay within what I asked for.",
  "Bring the requested task to its actual conclusion. Use the context already in this conversation.",
  "Bring the requested task to its actual conclusion. Do the next concrete step now.",
  "Bring the requested task to its actual conclusion. Do not add unrelated work.",
  "Bring the requested task to its actual conclusion. Keep the original requirements in view.",
  "Bring the requested task to its actual conclusion. Focus on the parts that are still incomplete.",
  "Bring the requested task to its actual conclusion. Respect the constraints I already gave you.",
  "Bring the requested task to its actual conclusion. Use the results you already have.",
  "Bring the requested task to its actual conclusion. Keep the update brief and get back to the work.",
  "Bring the requested task to its actual conclusion. Stop when the requested goal is fully complete.",
  "Keep making progress on the goal I gave you. Stay within what I asked for.",
  "Keep making progress on the goal I gave you. Use the context already in this conversation.",
  "Keep making progress on the goal I gave you. Do the next concrete step now.",
  "Keep making progress on the goal I gave you. Do not add unrelated work.",
  "Keep making progress on the goal I gave you. Keep the original requirements in view.",
  "Keep making progress on the goal I gave you. Focus on the parts that are still incomplete.",
  "Keep making progress on the goal I gave you. Respect the constraints I already gave you.",
  "Keep making progress on the goal I gave you. Use the results you already have.",
  "Keep making progress on the goal I gave you. Keep the update brief and get back to the work.",
  "Keep making progress on the goal I gave you. Stop when the requested goal is fully complete.",
  "Complete the required work that is still pending. Stay within what I asked for.",
  "Complete the required work that is still pending. Use the context already in this conversation.",
  "Complete the required work that is still pending. Do the next concrete step now.",
  "Complete the required work that is still pending. Do not add unrelated work.",
  "Complete the required work that is still pending. Keep the original requirements in view.",
  "Complete the required work that is still pending. Focus on the parts that are still incomplete.",
  "Complete the required work that is still pending. Respect the constraints I already gave you.",
  "Complete the required work that is still pending. Use the results you already have.",
  "Complete the required work that is still pending. Keep the update brief and get back to the work.",
  "Complete the required work that is still pending. Stop when the requested goal is fully complete.",
  "Continue the work you have already started. Stay within what I asked for.",
  "Continue the work you have already started. Use the context already in this conversation.",
  "Continue the work you have already started. Do the next concrete step now.",
  "Continue the work you have already started. Do not add unrelated work.",
  "Continue the work you have already started. Keep the original requirements in view.",
  "Continue the work you have already started. Focus on the parts that are still incomplete.",
  "Continue the work you have already started. Respect the constraints I already gave you.",
  "Continue the work you have already started. Use the results you already have.",
  "Continue the work you have already started. Keep the update brief and get back to the work.",
  "Continue the work you have already started. Stop when the requested goal is fully complete.",
  "Address the outstanding part of the original task. Stay within what I asked for.",
  "Address the outstanding part of the original task. Use the context already in this conversation.",
  "Address the outstanding part of the original task. Do the next concrete step now.",
  "Address the outstanding part of the original task. Do not add unrelated work.",
  "Address the outstanding part of the original task. Keep the original requirements in view.",
  "Address the outstanding part of the original task. Focus on the parts that are still incomplete.",
  "Address the outstanding part of the original task. Respect the constraints I already gave you.",
  "Address the outstanding part of the original task. Use the results you already have.",
  "Address the outstanding part of the original task. Keep the update brief and get back to the work.",
  "Address the outstanding part of the original task. Stop when the requested goal is fully complete.",
  "Keep going on the job until the requested result is ready. Stay within what I asked for.",
  "Keep going on the job until the requested result is ready. Use the context already in this conversation.",
  "Keep going on the job until the requested result is ready. Do the next concrete step now.",
  "Keep going on the job until the requested result is ready. Do not add unrelated work.",
  "Keep going on the job until the requested result is ready. Keep the original requirements in view.",
  "Keep going on the job until the requested result is ready. Focus on the parts that are still incomplete.",
  "Keep going on the job until the requested result is ready. Respect the constraints I already gave you.",
  "Keep going on the job until the requested result is ready. Use the results you already have.",
  "Keep going on the job until the requested result is ready. Keep the update brief and get back to the work.",
  "Keep going on the job until the requested result is ready. Stop when the requested goal is fully complete.",
  "Finish the remaining work instead of just promising it. Stay within what I asked for.",
  "Finish the remaining work instead of just promising it. Use the context already in this conversation.",
  "Finish the remaining work instead of just promising it. Do the next concrete step now.",
  "Finish the remaining work instead of just promising it. Do not add unrelated work.",
  "Finish the remaining work instead of just promising it. Keep the original requirements in view.",
  "Finish the remaining work instead of just promising it. Focus on the parts that are still incomplete.",
  "Finish the remaining work instead of just promising it. Respect the constraints I already gave you.",
  "Finish the remaining work instead of just promising it. Use the results you already have.",
  "Finish the remaining work instead of just promising it. Keep the update brief and get back to the work.",
  "Finish the remaining work instead of just promising it. Stop when the requested goal is fully complete."
];
export function templateGoalDecision(final: string, slot: number, secondSlot = slot + 1): { action: 'stop' } | { action: 'continue'; reply: string } | { action: 'invalid'; error: string } {
  const last = final.trim().split(/\r?\n/).at(-1)?.trim();
  if (last === '[[COS_GOAL:COMPLETE]]') return { action: 'stop' };
  if (last !== '[[COS_GOAL:CONTINUE]]') return { action: 'invalid', error: 'goal_marker_missing' };
  const first = Math.abs(Math.trunc(slot)) % GOAL_CONTINUATIONS.length;
  let second = Math.abs(Math.trunc(secondSlot)) % GOAL_CONTINUATIONS.length;
  if (second === first) second = (first + 1) % GOAL_CONTINUATIONS.length;
  return { action: 'continue', reply: `${GOAL_CONTINUATIONS[first]} ${GOAL_CONTINUATIONS[second]}` + GOAL_MARKER_INSTRUCTION };
}
